### ISSUE TITLE
Occasional json errors when creating note

### ISSUE THREAD

**Issue by kheerand** [kheerand/joplin_file_upload#7]
I suspect this is due to quotes " appearing in the body of the text, which confuses things.

**Comment by kheerand** [comment]
Still getting it even after I've added the `tostring` option

```
---Output
{"error":"Internal Server Error: Unexpected token \\ in JSON at position 148: \n\nSyntaxError: Unexpected token \\ in JSON at position 148\n    at JSON.parse (<anonymous>)\n    at Object.<anonymous> (C:\\Program Files\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\routes\\notes.js:348:38)\n    at Generator.next (<anonymous>)\n    at C:\\Program Files\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\routes\\notes.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Program Files\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\routes\\notes.js:4:12)\n    at Object.default_1 [as fn] (C:\\Program Files\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\routes\\notes.js:324:12)\n    at Api.<anonymous> (C:\\Program Files\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:114:41)\n    at Generator.next (<anonymous>)\n    at C:\\Program Files\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:8:71"}
---Cleanup uploaded files
```

**Comment by kheerand** [comment]
Looks like the fix was to do a quadruple backslash to escape enough times!

`sed 's/"/\\\\"/g` was the magic line!
